### ISSUE TITLE
[FEAT] Magento Coding Standards / PHP Compatibility tests

### ISSUE THREAD

**Issue by damienwebdev** [mage-os/github-actions#10]
# :bulb: Feature request

## Feature Name

Run Magento Coding Standards on top of my module(s)

## The Desired Behavior

I'd like to have the ability to run the Magento Coding Standards static test for my module from the module' or from the project's repository.
In addition to that, I'd like to select the Coding Standard version.

Also, I would like to have the ability to run PHP compatibility tests.

https://github.com/magento/magento-coding-standard
https://github.com/PHPCompatibility/PHPCompatibility

Note: here are the examples:
https://github.com/extdn/github-actions-m2/tree/master/magento-coding-standard
https://github.com/extdn/github-actions-m2/tree/master/magento-copy-paste-detector
https://github.com/extdn/github-actions-m2/tree/master/magento-mess-detector
https://github.com/extdn/github-actions-m2/tree/master/magento-phpstan
https://github.com/extdn/github-actions-m2/tree/master/php-compatibility

They are based on docker and do not support configuring the standard coding version, for instance.

**TODO**:
- [x] Run PHPCS on top of magento-coding-standard
- [ ] Run PHPCS for PHP compatibility
- [ ] Run PhpStan
- [ ] Run PHPMD
- [ ] Run Copy-Paste detector

## Environment

<pre><code>
Magento version: X.Y.Z 
PHP Version version: X.Y.Z 

Others:

</code></pre>

Copied from https://github.com/graycoreio/github-actions-magento2/issues/27 

cc: @ihor-sviziev
